INSERT INTO users (name, email, password) VALUES 
('Eva Stanley', 'sebastianguerra@ymail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Louisa Meyer', 'jacksonrose@hotmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Dominic Park', 'victoriablackwell@outlook.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Sue Luna', 'jasonvincent@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Rosalie Garza', 'jacksondavid@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Etta West', 'charlielevy@yahoo.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Margaret Wong', 'makaylaweiss@icloud.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Leroy Jenkins', 'jaycereynolds@inbox.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

INSERT INTO properties (owner_id, 
                        title, 
                        description, 
                        thumbnail_photo_url, 
                        cover_photo_url, 
                        cost_per_night, 
                        parking_space,
                        number_of_bathrooms,
                        number_of_bedrooms,
                        country,
                        street,
                        city,
                        province,
                        post_code) 
                                       VALUES (1, 
                                       'Speed lamp', 
                                       'description', 
                                       'thumbnail_photo_url', 
                                       'cover_photo_url',
                                       100,
                                       2,
                                       3,
                                       2,
                                       'United States',
                                       'Briard Drive',
                                       'Aplington',
                                       'Utah',
                                       'H3232-01'),
                                       (1, 
                                       'Blank corner', 
                                       'description', 
                                       'thumbnail_photo_url', 
                                       'cover_photo_url',
                                       200,
                                       2,
                                       3,
                                       2,
                                       'United States',
                                       'Middlebrook Trail',
                                       'Aplington',
                                       'Utah',
                                       'H3232-05'),
                                       (2, 
                                       'Blank corner', 
                                       'description', 
                                       'thumbnail_photo_url', 
                                       'cover_photo_url',
                                       150,
                                       4,
                                       2,
                                       2,
                                       'United States',
                                       'H Path',
                                       'Aplington',
                                       'Utah',
                                       'H3332-05');

INSERT INTO reservations (start_date, end_date, property_id, guest_id) 
VALUES ('2018-09-11', '2018-09-26', 2, 3), 
       ('2018-10-11', '2018-10-26', 3, 4),
       ('2018-02-11', '2018-02-16', 1, 5); 

INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) 
VALUES (1, 2, 10, 2, 'message'),
       (2, 3, 11, 4, 'message'),
       (8, 2, 12, 2, 'message');
                                       
                                       